{
 "title": "Monitoring 2",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Free space",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{mountpoint=\"/\"}"
    }
   ]
  },
  {
   "title": "Free mem",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemFree_bytes" }
   ]
  },
  {
   "title": "CPULA",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "node_load1", "legendFormat": "CPULA 1" },
    { "expr": "node_load5", "legendFormat": "CPULA 5" },
    { "expr": "node_load15", "legendFormat": "CPULA 15" }
   ]
  },
  {
   "title": "CPU Util",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (rate(node_cpu_seconds_total{cpu=\"0\", job=\"nodeexporter\", mode=\"idle\"}[1m]) * 100)",
     "legendFormat": "CPU0"
    },
    {
     "expr": "100 - (rate(node_cpu_seconds_total{cpu=\"1\", job=\"nodeexporter\", mode=\"idle\"}[1m]) * 100)",
     "legendFormat": "CPU1"
    }
   ]
  }
 ]
}